# Generated by Django 4.2.8 on 2024-01-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='raiting',
            new_name='rating',
        ),
    ]
