# Generated by Django 4.2.8 on 2024-01-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reset_pasword_expire',
            new_name='reset_password_expire',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='reset_pasword_token',
            new_name='reset_password_token',
        ),
    ]
